# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 2.7
  - 3.4
  - 3.5
addons:
    firefox: "52.0"
before_install:
  - pip install -U pip pytest wheel
  - python setup.py bdist_wheel
  - rm -rf kibitzr
install:
  - pip install dist/kibitzr*.whl
  - >
    curl -L https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
    | tar zxf -
    && sudo mv geckodriver /usr/local/bin/
  - pip install -e . -r requirements_dev.txt
before_script: flake8 kibitzr tests
script: py.test -v --cov kibitzr --cov-report term-missing
