# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 2.7
  - 3.4
  - 3.5
env:
  - SELENIUM_VERSION="<3.0"
  - SELENIUM_VERSION=">=3.0"
before_install:
  - pip install -U pip pytest
install:
  - pip install -e . -r requirements_dev.txt "selenium${SELENIUM_VERSION}"
  - >
    cd /usr/local/bin
    && curl -L https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
    | sudo tar zxf -
before_script: flake8 kibitzr tests
script: py.test -v --cov kibitzr --cov-report term-missing
